KW6_mailing/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('blog.urls', namespace='blog')),
    path('', include('users.urls', namespace='users'))
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path

from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView
from blog.apps import BlogConfig
from django.views.decorators.cache import cache_page

app_name = BlogConfig.name

urlpatterns = [

    path('blogs/', cache_page(60)(BlogListView.as_view()), name='blogs_view'),
    path('blogdetail/<slug:slug>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blogcreate/', BlogCreateView.as_view(), name='blog_create'),
    path('blogedit/<slug:slug>/', BlogUpdateView.as_view(), name='blog_edit'),
    # path('blogdelete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete')
    path('blogdelete/<slug:slug>/', BlogDeleteView.as_view(), name='blog_delete')

]

blog/models.py
from django.db import models

NULLABLE = {'null': True, 'blank': True}

class Blog(models.Model):
    title = models.CharField(max_length=250, verbose_name='title')
    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)
    text = models.TextField(verbose_name='text')
    image = models.ImageField(upload_to='blogs_images/', verbose_name='preview', **NULLABLE)
    date_created = models.DateTimeField(auto_now_add=True, verbose_name='date created')
    is_published = models.BooleanField(default=True, verbose_name='was published')
    counter_view = models.IntegerField(default=0, verbose_name='counter of views')

    def __str__(self):
        return f"{self.title} was created {self.date_created}"

    class Meta:
        verbose_name='blog'
        verbose_name_plural='blogs'
        ordering = ('date_created', )

blog/forms.py
from django import forms

from blog.models import Blog
from users.models import User


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field.widget, forms.widgets.CheckboxInput):
                field.widget.attrs['class'] = 'form-check-container'
            else:
                field.widget.attrs['class'] = 'form-control'


class BlogCreationForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Blog
        fields = '__all__'
        exclude = ('slug', 'counter_view')

blog/views.py
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, UpdateView, CreateView, DetailView, DeleteView
from pytils.translit import slugify

from blog.forms import BlogCreationForm
from blog.models import Blog
from blog.services import send_mail_to_admin
from config.config import THRESHOLD_VIEW_FOR_EMAIL


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.counter_view += 1
        if self.object.counter_view == THRESHOLD_VIEW_FOR_EMAIL:
            print('send mail to admin')
            send_mail_to_admin(self.object.pk)
        self.object.save()
        return self.object


class BlogCreateView(CreateView):
    model = Blog
    #fields = ['title', 'text', 'image']
    form_class = BlogCreationForm
    success_url = reverse_lazy('blog:blogs_view')

    def form_valid(self, form):
        """ add slug with testing by uniq slug string"""
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            if Blog.objects.filter(slug=new_blog.slug).exists():
                new_blog.slug = new_blog.slug + str(new_blog.pk)
            new_blog.save()
        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ['title', 'text', 'image', 'is_published']
    success_url = reverse_lazy('blog:blogs_view')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            if Blog.objects.filter(slug=new_blog.slug).exists():
                new_blog.slug = new_blog.slug + str(new_blog.pk)
            new_blog.save()
        return super().form_valid(form)

    def get_success_url(self):
        #return reverse('blog:blog_detail', args=[self.kwargs.get('slug')])
        return reverse('blog:blogs_view')


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blogs_view')

    def post(self, request, *args, **kwargs):
        where_a_u_from = request.META.get('HTTP_REFERER')
        # print(where_a_u_from)
        if "cancel" in request.POST:
            return redirect(request.META.get('HTTP_REFERER'))
        else:
            return super(BlogDeleteView, self).post(request, *args, **kwargs)

blog/templates/blog/blog_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    {% load my_tags %}
    <div class="container mt-6 md-5">
        <div class="row justify-content-center">
            <div class="col-md-6 col-lg-4">
                <div class="col-12">
                    <div class="card mb-4">
                         <div class="card-body">
                            <form method="post">{% csrf_token %}
                                <p>Are you sure you want to delete "{{ object }}"?</p>
                                <input type="submit" class="btn btn-danger" value="Confirm"/>
                                <input type="submit" class="btn btn-dark" value="Go back" name="cancel"/>
                                <a href="{% url 'blog:blogs_view' %}" class="btn btn-primary">Cancel</a>
                            </form>
                         </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'main/base.html' %}

{% block content %}
    {% load my_tags %}
    <div class="col-lg-10">
        <div class="content">
            <h2 class="card-title text-center mt-5">Blog detail</h2>
            <h3 class="card-title text-center mt-1">-----------</h3>
            <div class="container mt-6">
                <div class="row justify-content-center">
                        <div class="col-md-6 col-lg-4">
                            <div class="card text-center mb-4">
                                <div class="card-header">
                                    <h1>{{ object.title | title }}</h1>
                                </div>
                                <img class="card-img-top" src="{{  object.image | mediapath }}" alt="Goods image here">
                            </div>
                        </div>
                        <div class="col-md-12 col-lg-12">
                                <div class="card-body">
                                    <p class="card-text">{{ object.text}} </p>
                                    <p class="card-text"><b>was created  :</b>{{ object.date_created }}</p>
                                    <p class="card-text"><b>was published:  </b>{{ object.is_published }} </p>
                                    <p class="card-text"><b>slug is:        </b>{{ object.slug }}</p>
                                    {% if perms.blog.delete_blog %}
                                        <a href="{% url 'blog:blog_delete' object.pk %}" class="btn btn-primary">Delete</a>
                                    {% endif %}
                                </div>

                        </div>
                </div>
                <div class="card-footer">
                    views {{ object.counter_view }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'main/base.html' %}

{%  block content %}

<div class="col-lg-10">
    <div class="content">
        <h1 class="card-title text-center mt-5">Adding blog page</h1>
        <h3 class="card-title text-center mt-1">You can create new article here</h3>

        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <h2 class="text-center">Write here</h2>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}

                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Send</button>
                        </div>
                    </form>

                </div>
                <div class="col-lg-6">
                    <h2 class="text-center">Attention</h2>
                    <p>You can add new product here</p>
                    <p>be careful, validator doesn't work yet</p>
                    <p>in case of emergency write to</p>
                    <p>Email: info@example.com</p>
                </div>
            </div>
        </div>
    </div>
</div>
{%  endblock %}

blog/templates/blog/blog_list.html
{% extends 'main/base.html' %}
{% load my_tags %}

{%  block content %}
        <div class="col-lg-10">
            <div class="row justify-content-center mt-5">
                <div class="col-12">
                    <h2 class="text-center mb-4">Blogs</h2>
                    <div class="row">
                        {% for object in object_list %}
                        <div class="col-lg-3 col-md-3 col-sm-2">
                            <div class="card mb-4">
                                <div class="card-body">
                                    <h5 class="card-title">{{object.title}}</h5>
                                    <p class="card-text">This is blog {{object.pk}} id.</p>
                                    <div class="col-lg-12">
                                        <img class="card-img-right" alt="goods image" width="100" height="100" src="{{  object.image | mediapath }}" data-holder-rendered="false">
                                    </div>

                                    <div class="d-flex justify-content-start">
                                        <a href="{% url 'blog:blog_detail' object.slug %}" class="btn btn-primary" type="button">View</a>
                                        {% if perms.blog.change_blog %}
                                            <a href="{% url 'blog:blog_edit' object.slug %}" class="btn btn-secondary" type="button">Edit</a>
                                        {%  endif %}
                                        {% if perms.blog.delete_blog %}
                                            <a href="{% url 'blog:blog_delete' object.slug %}" class="btn btn-outline-dark" type="button">Delete</a>
                                        {% endif %}
                                    </div>

                                </div>
                            </div>
                        </div>
                        {% endfor %}

                    </div>
                    <div class="card-footer">
                            <a href="{% url 'blog:blog_create' %}" class="btn btn-primary">New Blog</a>
                    </div>
                </div>
            </div>
        </div>
{%  endblock %}
{#<b>#}

{#</b>#}