KW6_mailing/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('blog.urls', namespace='blog')),
    path('', include('users.urls', namespace='users'))
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path

from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView
from blog.apps import BlogConfig
from django.views.decorators.cache import cache_page

app_name = BlogConfig.name

urlpatterns = [

    path('blogs/', cache_page(60)(BlogListView.as_view()), name='blogs_view'),
    path('blogdetail/<slug:slug>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blogcreate/', BlogCreateView.as_view(), name='blog_create'),
    path('blogedit/<slug:slug>/', BlogUpdateView.as_view(), name='blog_edit'),
    # path('blogdelete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete')
    path('blogdelete/<slug:slug>/', BlogDeleteView.as_view(), name='blog_delete')

]

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import MailingListView, HomePageView, MailingListDetailView, MailingListCreateView, \
    MailingListUpdateView, MailingListDeleteView, MessageCreateView, ClientCreateView, home_page_view, mailing_activate, \
    mailing_deactivate, LogListView

app_name = MainConfig.name




urlpatterns = [
    path('', home_page_view, name='index'),
    path('index/', HomePageView.as_view(), name='index2'),
    path('mailinglist/', MailingListView.as_view(), name='mailing_list'),
    path('mailing/<int:pk>/', MailingListDetailView.as_view(), name='mailing_detail'),
    path('mailing/', MailingListCreateView.as_view(), name='mailing_create'),
    path('mailing/update/<int:pk>/', MailingListUpdateView.as_view(), name='mailing_update'),
    path('mailing/delete/<int:pk>/', MailingListDeleteView.as_view(), name='mailing_delete'),
    path('mailing/activate/<int:pk>/', mailing_activate, name='mailing_activate'),
    path('mailing/deactivate/<int:pk>/', mailing_deactivate, name='mailing_deactivate'),

    path('message/create/', MessageCreateView.as_view(), name='massage_create'),

    path('client/create/', ClientCreateView.as_view(), name='client_create'),

    path('log/', LogListView.as_view(), name='log_view'),
 ]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, MailWasSentView, UserConfirmEmailView, EmailConfirmedView, \
    MailConfirmationFailedView, generate_new_password, forgot_password, UsersListView, activate_user, deactivate_user

app_name = UsersConfig.name

urlpatterns = [
    #path('', LoginView.as_view(), name='login'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('mail_was_sent/', MailWasSentView.as_view(), name='mail_was_sent'),
    path('email_confirmed/', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('email_confirmation_failed/', MailConfirmationFailedView.as_view(), name='email_confirmation_failed'),
    path('confirm_email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('forgot_password/', forgot_password, name='forgot_password'),
    #path('generate_vew_password/', generate_new_password, name='generate_new_password'),
    path('users_view/', UsersListView.as_view(), name='users_view'),
    path('users_activate/<int:pk>', activate_user, name='users_activate'),
    path('users_deactivate/<int:pk>', deactivate_user, name='users_deactivate'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from main.models import NULLABLE


class User(AbstractUser):
    username = None
    email = models.EmailField(verbose_name='email', unique=True)
    phone = models.CharField(max_length=35, verbose_name='phone', **NULLABLE)
    country = models.CharField(max_length=50, verbose_name='country', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='avatar', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from users.models import User


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field.widget, forms.widgets.CheckboxInput):
                field.widget.attrs['class'] = 'form-check-container'
            else:
                field.widget.attrs['class'] = 'form-control'


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class ForgotForm(StyleFormMixin,forms.Form):
    email_address = forms.EmailField(max_length=150)


class UserProfileForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'country', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import string
from random import random, randint, choice

from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group
from django.contrib.auth.tokens import default_token_generator
# from django.contrib.sites.models import Site
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View
from django.views.generic import CreateView, UpdateView, TemplateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin

from KW6_mailing import settings
from users.forms import UserRegisterForm, UserProfileForm, ForgotForm
from users.models import User

from config.config import EMAIL_SENDING_SIMULATION_MODE


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        """ send token for registration confirm"""
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # Make and send the token
        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        activation_url = reverse_lazy('users:confirm_email', kwargs={'uidb64': uid, 'token': token})
        print(activation_url)
        # current_site = Site.objects.get_current().domain

        if not EMAIL_SENDING_SIMULATION_MODE:
            send_count = send_mail(
                subject='Confirm your registration',
                message=f'Please, follow the link to verify your email address:: http://127.0.0.1:8000{activation_url}',
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[user.email],
                # fail_silently=False,
            )
            print("send=", send_count)
        else:
            print("Simulation send email with token")
            print(f"activation line is: http://127.0.0.1:8000{activation_url}")
        return redirect('users:mail_was_sent')


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'users/profile.html'
    success_url = reverse_lazy('main:index')

    def get_object(self, request=None):
        return self.request.user


class MailWasSentView(TemplateView):
    template_name = 'users/mail_was_sent.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Mail was sent'
        return context


class UserConfirmEmailView(View):
    def get(self, request, uidb64, token):
        """handler for catch token response"""
        try:
            uid = urlsafe_base64_decode(uidb64)
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            group = Group.objects.get(name='operators')
            group.user_set.add(user)
            login(request, user)
            return redirect('users:email_confirmed')
        else:
            return redirect('users:email_confirmation_failed')


class EmailConfirmedView(TemplateView):
    template_name = 'users/email_confirmed.html'


class MailConfirmationFailedView(TemplateView):
    template_name = 'users/email_confirmation_failed.html'


def generate_new_password(challenger):
    """ would use it if you forgot your password
     new password will create and send to your email"""
    new_password = ''.join([str(choice(string.ascii_letters + string.digits)) for _ in range(6)])
    if User.objects.filter(email=challenger).exists():
        user = User.objects.get(email=challenger)
        # if user is None:
        #     return redirect('users:email_confirmation_failed')
        user.set_password(new_password)
        user.save()
        print(f"send email with new password {new_password}")
        if not EMAIL_SENDING_SIMULATION_MODE:
            send_mail(
                subject='Your new password',
                message=f'Your new password is : {new_password}',
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[user.email]
            )
        else:
            print(f"Simulate send email with new password {new_password} for user {[user.email]}")
    else:
        return redirect('users:email_confirmation_failed')
    return redirect('users:login')


def forgot_password(request):
    """ handler for button 'forgot password' """
    if request.method == 'POST':
        form = ForgotForm(request.POST)
        if form.is_valid():
            # form.save()
            challenger_email = form.cleaned_data['email_address']
            return generate_new_password(challenger_email)
    context = {'title': 'MicroShop email request', }
    form = ForgotForm()
    return render(request, 'users/forgot_password.html', {'form': form})


class UsersListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = User
    ordering = 'pk'
    permission_required = 'users.change_user'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['title'] = "User list"
        # interval = self.count_min_max_pk_on_page()
        return context


def activate_user(request, pk):
    """Let's activate user"""
    if User.objects.filter(pk=pk).exists():
        user = User.objects.get(pk=pk)
        if request.user.has_perm('users.change_user'):
            user.is_active = True
            user.save()
    return redirect('users:users_view')


def deactivate_user(request, pk):
    """ if I can deactivate I will do it,
    but I cannot change peer or superuser"""
    if User.objects.filter(pk=pk).exists():
        user = User.objects.get(pk=pk)
        if request.user.has_perm('users.change_user') \
                and not user.has_perm('users.change_user') \
                and not user.is_superuser:
            user.is_active = False
            user.save()
    return redirect('users:users_view')

users/templates/users/__login.html
{% load static %}
{#{% load crispy_forms_tags %}#}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Login</title>

    <style>
        html,
        body {
            height: 100%;
        }

        body {
            display: -ms-flexbox;
            display: -webkit-box;
            display: flex;
            -ms-flex-align: center;
            -ms-flex-pack: center;
            -webkit-box-align: center;
            align-items: center;
            -webkit-box-pack: center;
            justify-content: center;
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }

        .form-signin {
            width: 100%;
            max-width: 330px;
            padding: 15px;
            margin: 0 auto;
        }

        .form-signin .checkbox {
            font-weight: 400;
        }

        .form-signin .form-control {
            position: relative;
            box-sizing: border-box;
            height: auto;
            padding: 10px;
            font-size: 16px;
        }

        .form-signin .form-control:focus {
            z-index: 2;
        }

        .form-signin input[type="email"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
    </style>

    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">

</head>

<body class="text-center">
<form class="form-signin" method="post">
    {% csrf_token %}
    <div class="card p-5">
        {% crispy form %}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>

        <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>
    </div>
</form>
</body>
</html>

users/templates/users/email_confirmation_failed.html
{% extends "main/base.html" %}



{% block content %}

    <div class="container lg-6 mt-6 md-5">
                    <div class="card lg-4 mb-4">
                         <div class="alert alert-warning" role="alert">
                                <h3 class="alert-heading"> Sorry. Activation has not been successful</h3>
                         </div>
                    </div>
    </div>
{% endblock %}

users/templates/users/email_confirmed.html
{% extends "main/base.html" %}



{% block content %}

    <div class="container lg-6 mt-6 md-5">
                    <div class="card lg-4 mb-4">
                         <div class="alert alert-success" role="alert">
                                <h3 class="alert-heading"> Congratulation. Activation has been successful</h3>
                         </div>
                    </div>
    </div>
{% endblock %}

users/templates/users/forgot_password.html
{% extends 'main/base.html' %}

{%  block content %}


{#<section class="h-100 gradient-form" style="background-color: #eee;">#}
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-xl-10">
        <div class="card rounded-3 text-black">
          <div class="row g-0">
            <div class="col-lg-12">
{#              <div class="card-body p-md-5 mx-md-4">#}


                <form method="post" enctype="multipart/form-data">
                  <h3>Please enter your email</h3>

                 <div class="card-body">
                     {% csrf_token %}
                        {{ form.as_p }}
                 </div>

                  <div class="text-center pt-1 mb-5 pb-1">
                    <button class="btn btn-primary btn-block fa-lg gradient-custom-2 mb-3" type="submit">Send new password</button>
                   </div>



                </form>

{#              </div>#}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{#</section>#}
    {% endblock %}

users/templates/users/login.html
{% extends 'main/base.html' %}

{%  block content %}


<section class="h-100 gradient-form" style="background-color: #eee;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-xl-10">
        <div class="card rounded-3 text-black">
          <div class="row g-0">
            <div class="col-lg-6">
              <div class="card-body p-md-5 mx-md-4">

                <div class="text-center">
                  <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/lotus.webp"
                    style="width: 185px;" alt="logo">
                  <h4 class="mt-1 mb-5 pb-1">We are {{  title }}</h4>
                </div>

                <form method="post" enctype="multipart/form-data">
                  <p>Please login to your account</p>

                 <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                 </div>

                  <div class="text-center pt-1 mb-5 pb-1">
                    <button class="btn btn-primary btn-block fa-lg gradient-custom-2 mb-3" type="submit">Login</button>
                    <a class="text-muted" href="{% url 'users:forgot_password' %}">Forgot password?</a>
                  </div>

                  <div class="d-flex align-items-center justify-content-center pb-4">
                    <p class="mb-0 me-2">Don't have an account?</p>
                    <a href="{% url 'users:register' %}" class="btn btn-outline-danger">Create new</a>
                  </div>

                </form>

              </div>
            </div>
            <div class="col-lg-6 d-flex align-items-center gradient-custom-2">
              <div class="text-white px-3 py-4 p-md-5 mx-md-4">
                <h4 class="mb-4">We are more than just a company</h4>
                <p class="small mb-0">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
                  exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

users/templates/users/mail_was_sent.html
{% extends "main/base.html" %}



{% block content %}

    <div class="container lg-6 mt-6 md-5">
                    <div class="card lg-4 mb-4">
                         <div class="alert alert-info" role="alert">
                                <h3 class="alert-heading"> On you email was sent link for activation</h3>
                         </div>
                    </div>
    </div>
{% endblock %}

users/templates/users/profile.html
{% extends 'main/base.html' %}

{%  block content %}


<section class="col-lg-6 h-100 gradient-form" style="background-color: #eee;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-xl-10">
        <div class="card rounded-3 text-black">
          <div class="row g-0">
{#            <div class="col-lg-6">#}
              <div class="card-body p-md-5 mx-md-4">

                <div class="text-center">
                  <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/lotus.webp"
                    style="width: 185px;" alt="logo">
                  <h4 class="mt-1 mb-5 pb-1">Profile edit page</h4>
                </div>

                <form method="post" enctype="multipart/form-data">
                  <p>your can change your profile</p>

                 <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                 </div>

                  <div class="text-center pt-1 mb-5 pb-1">
                    <button class="btn btn-primary btn-block fa-lg gradient-custom-2 mb-3" type="submit">Save</button>
                  </div>


                </form>

              </div>
{#            </div>#}
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

users/templates/users/register.html
{% extends 'main/base.html' %}

{%  block content %}


<section class="h-100 gradient-form" style="background-color: #eee;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-xl-10">
        <div class="card rounded-3 text-black">
          <div class="row g-0">
{#            <div class="col-lg-6">#}
              <div class="card-body p-md-5 mx-md-4">
{##}
{#                <div class="text-center">#}
{#                  <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/lotus.webp"#}
{#                    style="width: 185px;" alt="logo">#}
{#                  <h4 class="mt-1 mb-5 pb-1">We are {{  title }}</h4>#}
{#                </div>#}

                <form method="post" enctype="multipart/form-data">
                  <h3>Please enter your email and password for account</h3>

                 <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                 </div>

                  <div class="text-center pt-1 mb-5 pb-1">
                    <button class="btn btn-primary btn-block fa-lg gradient-custom-2 mb-3" type="submit">Save</button>
                    <a class="text-muted" href="#!">Forgot password?</a>
                  </div>


                </form>

              </div>
{#            </div>#}
{#            <div class="col-lg-6 d-flex align-items-center gradient-custom-2">#}
{#              <div class="text-white px-3 py-4 p-md-5 mx-md-4">#}
{#                <h4 class="mb-4">We are more than just a company</h4>#}
{#                <p class="small mb-0">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod#}
{#                  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud#}
{#                  exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>#}
{#              </div>#}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

users/templates/users/user_list.html
{% extends 'main/base.html' %}

{%  block content %}
<div class="col-lg-10">
    <div class="content">
        <h1 class="card-title text-center mt-5">Users list page</h1>
{#        <a href="{% url 'main:mailing_create' %}" class="btn btn-primary">Add new mailing</a>#}
        <div class="container mt-5 overflow-hidden">
            <div class="row">
                {% for object in object_list %}
                    <div class="pb-3">
                    <div class="col-lg-12 col-md-12">
                        <div class="card text-center">
                            <div class="card-header">
                                <h5> {{ object.email }} </h5>
                                <div class="text-right">
                                {% if request.user.is_authenticated %}
                                    {% if object.is_active %}
                                    <a href="{% url 'users:users_deactivate' object.pk %}" class="btn btn-danger">DeActivate</a>
                                    {% else %}
                                        <a href="{% url 'users:users_activate' object.pk %}" class="btn btn-primary">Activate</a>
{#                                        {% if object.status == 'is active' %}#}
{#                                            <a href="{% url 'main:mailing_deactivate' object.pk %}" class="btn btn-primary">Close</a>#}
{#                                        {% else %}#}
{#                                            <p> Completed and closed </p>#}
{#                                        {% endif %}#}
                                    {% endif %}
                                {% endif %}
                                </div>
                            </div>
                            <div class="card-body text-left">
                                <p><b>first name:</b>{{ object.first_name }}</p>
                                <p><b>last name:</b>{{ object.last_name}}</p>
                                <p><b>phone:</b>{{ object.phone }}</p>
                                <p><b>country:</b>{{ object.country }}</p>
{#                                <div class="text-right">#}
{#                                    <a href="{% url 'main:mailing_delete' object.pk %}" class="btn btn-danger">Delete</a>#}
{#                                    <a href="{% url 'main:mailing_update' object.pk %}" class="btn btn-secondary">Edit</a>#}
{#                                </div>#}
                            </div>
                        </div>
                    </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}