KW6_mailing/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('blog.urls', namespace='blog')),
    path('', include('users.urls', namespace='users'))
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path

from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView
from blog.apps import BlogConfig
from django.views.decorators.cache import cache_page

app_name = BlogConfig.name

urlpatterns = [

    path('blogs/', cache_page(60)(BlogListView.as_view()), name='blogs_view'),
    path('blogdetail/<slug:slug>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blogcreate/', BlogCreateView.as_view(), name='blog_create'),
    path('blogedit/<slug:slug>/', BlogUpdateView.as_view(), name='blog_edit'),
    # path('blogdelete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete')
    path('blogdelete/<slug:slug>/', BlogDeleteView.as_view(), name='blog_delete')

]

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import MailingListView, HomePageView, MailingListDetailView, MailingListCreateView, \
    MailingListUpdateView, MailingListDeleteView, MessageCreateView, ClientCreateView, home_page_view, mailing_activate, \
    mailing_deactivate, LogListView

app_name = MainConfig.name




urlpatterns = [
    path('', home_page_view, name='index'),
    path('index/', HomePageView.as_view(), name='index2'),
    path('mailinglist/', MailingListView.as_view(), name='mailing_list'),
    path('mailing/<int:pk>/', MailingListDetailView.as_view(), name='mailing_detail'),
    path('mailing/', MailingListCreateView.as_view(), name='mailing_create'),
    path('mailing/update/<int:pk>/', MailingListUpdateView.as_view(), name='mailing_update'),
    path('mailing/delete/<int:pk>/', MailingListDeleteView.as_view(), name='mailing_delete'),
    path('mailing/activate/<int:pk>/', mailing_activate, name='mailing_activate'),
    path('mailing/deactivate/<int:pk>/', mailing_deactivate, name='mailing_deactivate'),

    path('message/create/', MessageCreateView.as_view(), name='massage_create'),

    path('client/create/', ClientCreateView.as_view(), name='client_create'),

    path('log/', LogListView.as_view(), name='log_view'),
 ]

main/models.py
from django.db import models
from django.utils.datetime_safe import datetime

from KW6_mailing import settings

NULLABLE = {'null': True, 'blank': True}


class Client(models.Model):
    first_name = models.CharField(max_length=150, verbose_name='first_name', **NULLABLE)
    last_name = models.CharField(max_length=150, verbose_name='last_name', **NULLABLE)
    email = models.EmailField(max_length=150, verbose_name='email')
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='creator')
    is_active = models.BooleanField(default=True, verbose_name='is_active')

    def __str__(self):
        return f'{self.email}'

    class Meta:
        verbose_name = 'Client'
        verbose_name_plural = 'Clients'
        ordering = ('last_name',)
        get_latest_by = 'email'


class MailingMessage(models.Model):
    subject = models.CharField(max_length=200, verbose_name='subject')
    body = models.TextField(verbose_name='body')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='creation time')
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='creator')

    def __str__(self):
        # return f'{self.subject} created at {self.created_time.strftime("%Y-%m-%d %H:%M")}'
        return f'{self.subject}'


    class Meta:
        verbose_name = 'message'
        verbose_name_plural = 'messages'


class MailingList(models.Model):
    ONCE = 'onetime'
    DAILY = 'daily'
    WEEKLY = 'weekly'
    MONTHLY = 'monthly'

    PERIODICITY = [
        (ONCE, 'onetime'),
        (DAILY, 'daily'),
        (WEEKLY, 'weekly'),
        (MONTHLY, 'monthly'),
    ]

    CREATED = 'was created'
    COMPLETED = 'was ended'
    ACTIVE = 'is active'

    SELECT_STATUS = [
        (CREATED, 'was created'),
        (COMPLETED, 'was ended'),
        (ACTIVE, 'active'),
    ]

    client_id = models.ManyToManyField(Client, verbose_name='client id')
    message = models.ForeignKey(MailingMessage, on_delete=models.CASCADE, verbose_name='message')
    time = models.TimeField(default=datetime.now, verbose_name='time')
    start = models.DateTimeField(default=datetime.now, verbose_name='start time UTC')
    finish = models.DateTimeField(default=datetime.now, verbose_name='finish time UTC')
    periodicity = models.CharField(max_length=150, choices=PERIODICITY, verbose_name='periodicity')
    status = models.CharField(max_length=100, default='was created', choices=SELECT_STATUS, verbose_name='status')
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='creator')

    def __str__(self):
        return f"{self.message.subject} have to start from {self.start.strftime('%Y-%m-%d %H:%M')} with period {self.periodicity}"

    class Meta:
        verbose_name = 'mailing list'
        verbose_name_plural = 'mailing lists'
        get_latest_by = 'time'
        permissions = [
                ('change_active', 'Can change active flag')
            ]


class MailingListLogs(models.Model):
    SENT = 'was sent'
    ERROR = 'sending error'

    STATUS = (
        (SENT, 'sent'),
        (ERROR, 'sending error'),
    )

    mailing_list_id = models.ForeignKey(MailingList, on_delete=models.CASCADE, verbose_name='mailing list id')
    client = models.ForeignKey(Client, on_delete=models.CASCADE, **NULLABLE, verbose_name='client')
    send_time = models.DateTimeField(auto_now_add=True, verbose_name='send time')
    status = models.CharField(choices=STATUS, verbose_name='status')
    response = models.TextField(**NULLABLE, verbose_name='response from server')

    def __str__(self):
        return f'{self.mailing_list_id.message.subject} was processed: {self.send_time.strftime("%Y-%m-%d %H:%M")}'

    class Meta:
        verbose_name = 'mailing effort log'
        verbose_name_plural = 'mailing efforts log'

main/forms.py
from django import forms

from main.models import MailingList, MailingMessage, Client


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field.widget, forms.widgets.CheckboxInput):
                field.widget.attrs['class'] = 'form-check-container'
            else:
                field.widget.attrs['class'] = 'form-control'


class MailingListCreationForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = MailingList
        # fields = '__all__'
        exclude = ('creator',)

    def clean_finish(self):
        finish = self.cleaned_data['finish']
        start = self.cleaned_data['start']
        if start > finish:
            raise forms.ValidationError('Attention! Finish time cannot be less then start')
        if start == finish:
            raise forms.ValidationError('Attention! Finish time need to be more then start at least 5 min')

        return finish


class MessageCreationForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = MailingMessage
        exclude = ('creator',)

class ClientCreateForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        fields = ('email', 'first_name', 'last_name', 'is_active')
        # exclude = ('creator',)

main/views.py
import random

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from blog.models import Blog
# from config.config import MAX_PRODUCTS_PER_PAGE
from main.forms import MailingListCreationForm, MessageCreationForm, ClientCreateForm
from main.models import MailingList, MailingMessage, Client, MailingListLogs
from main.services import checking_and_send_emails, get_log_data


class HomePageView(ListView):
    model = MailingList
    template_name = 'main/index.html'


# HomePage View in FBV notation
def home_page_view(request):
    blogs = Blog.objects.all()
    blogs_count = Blog.objects.count()
    if blogs_count > 3:
        selected_numbers = random.sample(list(range(blogs_count)), k=3)
        blogs = [blogs[selected_numbers[0]], blogs[selected_numbers[1]], blogs[selected_numbers[2]]]
    mailing_count = MailingList.objects.count()
    mailing_active_count = MailingList.objects.filter(status='is active').count()
    uniq_clients_count = Client.objects.all().count()
    context = {'object_list': blogs,
               'title': "Mailing service",
               'uniq_clients_count': uniq_clients_count,
               'mailing_count': mailing_count,
               'mailing_active_count': mailing_active_count}
    return render(request, 'main/index.html', context)


class MailingListView(LoginRequiredMixin, ListView):
    model = MailingList
    ordering = 'pk'

    def get_queryset(self, *args, **kwargs):
        # print(self.request.user.groups.filter(name='Managers'))
        if self.request.user.groups.filter(name='managers').exists() or self.request.user.is_superuser:
            context = super().get_queryset()
        else:
            context = MailingList.objects.filter(creator=self.request.user)
        return context

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['title'] = "Mailing service"
        context['managers'] = self.request.user.groups.filter(name='managers').exists()
        # interval = self.count_min_max_pk_on_page()
        return context


class MailingListDetailView(LoginRequiredMixin, DetailView):
    model = MailingList
    success_url = reverse_lazy('main:mailing_list')

    # permission_required = ('main.view_mailinglist', )

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['title'] = "Mailing service"
        # interval = self.count_min_max_pk_on_page()
        return context


class MailingListCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = MailingList
    form_class = MailingListCreationForm
    success_url = reverse_lazy('main:mailing_list')
    permission_required = ('main.add_mailinglist',)

    def form_valid(self, form):
        """ save data
         after that we will immediately check and send the mail if necessary """
        self.object = form.save()
        self.object.creator = self.request.user
        self.object.save()
        checking_and_send_emails()
        return super().form_valid(form)


class MailingListUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = MailingList
    template_name = 'main/mailinglist_form.html'
    success_url = reverse_lazy('main:mailing_list')
    form_class = MailingListCreationForm
    permission_required = ('main.change_mailinglist',)

    def form_valid(self, form):
        """ save new data
        after that we will immediately check and send the mail if necessary """
        self.object = form.save()
        self.object.creator = self.request.user
        self.object.save()
        checking_and_send_emails()
        return super().form_valid(form)


class MailingListDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = MailingList
    success_url = reverse_lazy('main:mailing_list')
    permission_required = ('main.delete_mailinglist',)


def mailing_activate(request, pk):
    """set status 'is active' for current object
       after that we will immediately check and send the mail if necessary """
    info = get_object_or_404(MailingList, pk=pk)
    info.status = 'is active'
    info.save()
    print(info)
    checking_and_send_emails()
    return redirect('main:mailing_list')


def mailing_deactivate(request, pk):
    """set status 'was ended' for current object"""
    obj = get_object_or_404(MailingList, pk=pk)
    obj.status = 'was ended'
    obj.save()
    return redirect('main:mailing_list')


class MessageCreateView(CreateView):
    model = MailingMessage
    form_class = MessageCreationForm
    success_url = reverse_lazy('main:mailing_create')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Message Creation"
        return context

    def form_valid(self, form):
        self.object = form.save()
        self.object.creator = self.request.user
        self.object.save()
        return super().form_valid(form)


class ClientCreateView(LoginRequiredMixin, PermissionRequiredMixin,CreateView):
    model = Client
    success_url = reverse_lazy('main:mailing_list')
    form_class = ClientCreateForm

    permission_required = ('main.view_client', )


class LogListView(ListView):
    model = MailingListLogs
    # success_url = reverse_lazy('main:mailing_list')
    fields = ('send_time', 'status', 'response')

    def get_queryset(self, *args, **kwargs):
        """ rewrite for using low-level cache"""
        return get_log_data()

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <style>
        body {
            min-height: 100vh;
            display: flex;
            flex-direction: column;
        }

        .content {
            flex-grow: 1;
        }
    </style>

</head>
<body>
<div class="container-fluid h-100">
    <div class="row h-100">
        {% include 'main/includes/inc_main_menu.html' %}
        {% block content %}
        {% endblock %}
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script type="text/javascript">
    var currentLocation = window.location.href
    var menuItems = document.querySelectorAll('a');
    for (var i = 0; i < menuItems.length; i++) {
        if (menuItems[i].href === currentLocation) {
            menuItems[i].classList.add('active');
        }
    }
</script>
</body>
</html>

main/templates/main/client_form.html
{% extends 'main/base.html' %}

{%  block content %}

<div class="col-lg-10">
    <div class="content">
        <h1 class="card-title text-center mt-5">Adding new client</h1>
        <h3 class="card-title text-center mt-1">You can create new client here</h3>

        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <h3 class="text-center">Write here</h3>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}

                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Save client information</button>
                        </div>
                    </form>
                </div>
{#                <div class="col-lg-6">#}
{#                    <h2 class="text-center">Attention</h2>#}
{#                    <div class="text-center">#}
{#                        <p>You can add new mailing list here</p>#}
{#                        <p>be careful, choose correct message</p>#}
{#                        <p>in case of emergency write to</p>#}
{#                        <p>Email: info@example.com</p>#}
{#                        <p>If you can't find message what you need to send,</p>#}
{#                        <p>You have to create a new one</p>#}
{#                        <a href="{% url 'main:massage_create' %}" class="btn btn-danger">Create new message</a>#}
{#                    </div>#}
{#                </div>#}
            </div>
        </div>
    </div>
</div>
{%  endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load my_tags %}

{% block content %}
    <div class="col-lg-10">
        <div class="content">
            <h1 class="card-title text-center mt-5">Main page</h1>
            <h3 class="card-title text-center mt-1">Welcome to our mailing service</h3>
            <div class="container mt-5">
                <div class="row justify-content-center">
                    {% for object in object_list %}
                        <div class="col-3">
                            <div class="card text-center">
                                <div class="card-header">
                                    {{ object.title | title  | truncatechars:30}}
                                </div>
                                <div class="card-body">
                                    <div class="col-lg-12">
                                        <img class="card-img-right" alt="goods image" width="150" height="150" src="{{  object.image | mediapath }}" data-holder-rendered="false">
                                    </div>

                                    {{ object.text | truncatechars:100}}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="b-example-divider"></div>
            <div class="container">
            <div class="card-footer py-3 my-4">
{#            <footer class="py-3 my-4">#}
                <b class="text-center text-body-secondary">mailing count: {{ mailing_count }}, active mailing
                    count:{{ mailing_active_count }}, Clients for mailing: {{ uniq_clients_count }}</b>
                <b class="text-right text-body-secondary">&copy; 2023 {{ title }}</b>
{#            </footer>#}
            </div>
            </div>
        </div>
    </div>

{% endblock %}>

main/templates/main/mailinglist_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    Are you sure you want to delete "{{ object }}"?<br>
                    <input type="submit" class="btn btn-outline-danger" value="Confirm">
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'main:mailing_list' %}" class="btn btn-primary"><< Back</a>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/mailinglist_detail.html
{% extends 'main/base.html' %}

{% block content %}
    {% load my_tags %}
    <div class="col-lg-10">
        <div class="content">
            <h1 class="card-title text-center mt-5">Details of one mailing</h1>
{#            <h3 class="card-title text-center mt-1"> all what I know (c) {{ title }}</h3>#}
            <div class="container mt-5">
                <div class="row justify-content-center">
{#                    {% for object in object_list %}#}
                        <div class="col-md-6 col-lg-4">
                            <div class="card text-center mb-4">
                                <div class="card-header">
                                    <h5> {{ object.message | title }} </h5>
                                </div>
{#                                <img class="card-img-top" src="{% mediapath object.image %}" alt="Goods image here">#}
{#                                <img class="card-img-top" src="{{  object.image | mediapath }}" alt="Goods image here">#}
                                <div class="card-body">
                                    <p class="card-title">Status:{{ object.status }}</p>
{#                                  <ul class="list-unstyled mt-3 mb-4 text-start m-3">#}
                                    <p class="card-text">Start:{{ object.start}} </p>
{#                                  </u>#}
                                    <p class="card-text">Clients:{{ object.client_id }}</p>
                                    <p class="card-text">Finish:{{ object.finish }}</p>
{#                                    {% for ver in versions %}#}
{#                                        <p class="card-text"> <b>version:</b>{{ ver.version_number }} </p>#}
{#                                    {% endfor %}#}
{#                                    <a href="#" class="btn btn-primary">Buy</a>#}
                                    <a href="{% url 'main:mailing_update' object.pk %}" class="btn btn-danger">Edit</a>
                                </div>
                            </div>
                        </div>
{#                    {% endfor %}#}
                </div>

            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/mailinglist_form.html
{% extends 'main/base.html' %}

{%  block content %}

<div class="col-lg-10">
    <div class="content">
        <h1 class="card-title text-center mt-5">Adding page</h1>
        <h3 class="card-title text-center mt-1">You can create new mail list here</h3>

        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <h2 class="text-center">Write here</h2>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}

                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Save Mailing</button>
                        </div>
                    </form>
                </div>
                <div class="col-lg-6">
                    <h2 class="text-center">Attention</h2>
                    <div class="text-center">
                        <p>You can add new mailing list here</p>
                        <p>be careful, choose correct message</p>
                        <p>in case of emergency write to</p>
                        <p>Email: info@example.com</p>
                        <p>If you can't find message what you need to send,</p>
                        <p>You have to create a new one</p>
                        <a href="{% url 'main:massage_create' %}" class="btn btn-danger">Create new message</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{%  endblock %}

main/templates/main/mailinglist_list.html
{% extends 'main/base.html' %}

{%  block content %}
<div class="col-lg-10">
    <div class="content">
        <h1 class="card-title text-center mt-5">Mailing list page</h1>
        {% if not managers %}
            <a href="{% url 'main:mailing_create' %}" class="btn btn-primary">Add new mailing</a>
        {% endif %}
        <div class="container mt-5 overflow-hidden">
            <div class="row">
                {% for object in object_list %}
                    <div class="pb-3">
                    <div class="col-lg-12 col-md-12">
                        <div class="card text-center">
                            <div class="card-header">
                                <h5> {{ object.message | title }}   </h5>
                                <div class="text-right">
                                    {% if object.status == 'was created' %}
                                    <a href="{% url 'main:mailing_activate' object.pk %}" class="btn btn-primary">Activate</a>
                                    {% else %}
                                        {% if object.status == 'is active' %}
                                            <a href="{% url 'main:mailing_deactivate' object.pk %}" class="btn btn-primary">Close</a>
                                        {% else %}
                                            <p> Completed and closed </p>
                                        {% endif %}
                                    {% endif %}
                                </div>
                            </div>
                            <div class="card-body text-left">
                                <b>start time:</b>{{ object.start }}
                                <b>finish time:</b>{{ object.finish }}
                                <b>periodicity:</b>{{ object.periodicity }}
                                <b>Status:</b>{{ object.status }}
                                <div class="text-right">
                                    {% if not managers %}
                                        <a href="{% url 'main:mailing_delete' object.pk %}" class="btn btn-danger">Delete</a>
                                        <a href="{% url 'main:mailing_update' object.pk %}" class="btn btn-secondary">Edit</a>
                                    {%  endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/mailinglistlogs_list.html
{% extends 'main/base.html' %}
{% load my_tags %}

{%  block content %}
<div class="col-lg-10">
    <div class="content">
        <h1 class="card-title text-center mt-5">Mailing log</h1>
        <div class="container mt-5 overflow-hidden">
            <div class="row">
                {% for object in object_list %}
                    <div class="col-lg-12 col-md-12">
                        <p> {{ object.send_time | cut_time }} mailing: <b> {{ object.mailing_list_id }} ; </b>
                                <b>Status:</b>{{ object.status }};
                                <b>start time:</b>{{ object.mailing_list_id.start | cut_time }};
                                <b>finish time:</b>{{ object.mailing_list_id.finish | cut_time }};
                                <b>response:</b>{{ object.response }};
                                <b>client:</b>{{ object.client }};
                        </p>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/mailingmessage_form.html
{% extends 'main/base.html' %}

{%  block content %}

<div class="col-lg-10">
    <div class="content">
        <h1 class="card-title text-center mt-5">Adding new message</h1>
        <h3 class="card-title text-center mt-1">You can create new message here</h3>

        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-lg-6">
{#                    <h2 class="text-center">Write here</h2>#}
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}

                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </form>
                </div>
{#                <div class="col-lg-6">#}
{#                    <h2 class="text-center">Attention</h2>#}
{#                    <div class="text-center">#}
{#                        <p>You can add new mailing list here</p>#}
{#                        <p>be careful, choose correct message</p>#}
{#                        <p>in case of emergency write to</p>#}
{#                        <p>Email: info@example.com</p>#}
{#                        <p>If you can't find message what you need to send,</p>#}
{#                        <p>You have to create a new one</p>#}
{#                        <a href="{% url 'main:massage_create' %}" class="btn btn-danger">Create</a>#}
{#                    </div>#}
{#                </div>#}
            </div>
        </div>
    </div>
</div>
{%  endblock %}