KW6_mailing/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('blog.urls', namespace='blog')),
    path('', include('users.urls', namespace='users'))
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path

from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView
from blog.apps import BlogConfig
from django.views.decorators.cache import cache_page

app_name = BlogConfig.name

urlpatterns = [

    path('blogs/', cache_page(60)(BlogListView.as_view()), name='blogs_view'),
    path('blogdetail/<slug:slug>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blogcreate/', BlogCreateView.as_view(), name='blog_create'),
    path('blogedit/<slug:slug>/', BlogUpdateView.as_view(), name='blog_edit'),
    # path('blogdelete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete')
    path('blogdelete/<slug:slug>/', BlogDeleteView.as_view(), name='blog_delete')

]

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import MailingListView, HomePageView, MailingListDetailView, MailingListCreateView, \
    MailingListUpdateView, MailingListDeleteView, MessageCreateView, ClientCreateView, home_page_view, mailing_activate, \
    mailing_deactivate, LogListView

app_name = MainConfig.name




urlpatterns = [
    path('', home_page_view, name='index'),
    path('index/', HomePageView.as_view(), name='index2'),
    path('mailinglist/', MailingListView.as_view(), name='mailing_list'),
    path('mailing/<int:pk>/', MailingListDetailView.as_view(), name='mailing_detail'),
    path('mailing/', MailingListCreateView.as_view(), name='mailing_create'),
    path('mailing/update/<int:pk>/', MailingListUpdateView.as_view(), name='mailing_update'),
    path('mailing/delete/<int:pk>/', MailingListDeleteView.as_view(), name='mailing_delete'),
    path('mailing/activate/<int:pk>/', mailing_activate, name='mailing_activate'),
    path('mailing/deactivate/<int:pk>/', mailing_deactivate, name='mailing_deactivate'),

    path('message/create/', MessageCreateView.as_view(), name='massage_create'),

    path('client/create/', ClientCreateView.as_view(), name='client_create'),

    path('log/', LogListView.as_view(), name='log_view'),
 ]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, MailWasSentView, UserConfirmEmailView, EmailConfirmedView, \
    MailConfirmationFailedView, generate_new_password, forgot_password, UsersListView, activate_user, deactivate_user

app_name = UsersConfig.name

urlpatterns = [
    #path('', LoginView.as_view(), name='login'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('mail_was_sent/', MailWasSentView.as_view(), name='mail_was_sent'),
    path('email_confirmed/', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('email_confirmation_failed/', MailConfirmationFailedView.as_view(), name='email_confirmation_failed'),
    path('confirm_email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('forgot_password/', forgot_password, name='forgot_password'),
    #path('generate_vew_password/', generate_new_password, name='generate_new_password'),
    path('users_view/', UsersListView.as_view(), name='users_view'),
    path('users_activate/<int:pk>', activate_user, name='users_activate'),
    path('users_deactivate/<int:pk>', deactivate_user, name='users_deactivate'),
]

main/models.py
from django.db import models
from django.utils.datetime_safe import datetime

from KW6_mailing import settings

NULLABLE = {'null': True, 'blank': True}


class Client(models.Model):
    first_name = models.CharField(max_length=150, verbose_name='first_name', **NULLABLE)
    last_name = models.CharField(max_length=150, verbose_name='last_name', **NULLABLE)
    email = models.EmailField(max_length=150, verbose_name='email')
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='creator')
    is_active = models.BooleanField(default=True, verbose_name='is_active')

    def __str__(self):
        return f'{self.email}'

    class Meta:
        verbose_name = 'Client'
        verbose_name_plural = 'Clients'
        ordering = ('last_name',)
        get_latest_by = 'email'


class MailingMessage(models.Model):
    subject = models.CharField(max_length=200, verbose_name='subject')
    body = models.TextField(verbose_name='body')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='creation time')
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='creator')

    def __str__(self):
        # return f'{self.subject} created at {self.created_time.strftime("%Y-%m-%d %H:%M")}'
        return f'{self.subject}'


    class Meta:
        verbose_name = 'message'
        verbose_name_plural = 'messages'


class MailingList(models.Model):
    ONCE = 'onetime'
    DAILY = 'daily'
    WEEKLY = 'weekly'
    MONTHLY = 'monthly'

    PERIODICITY = [
        (ONCE, 'onetime'),
        (DAILY, 'daily'),
        (WEEKLY, 'weekly'),
        (MONTHLY, 'monthly'),
    ]

    CREATED = 'was created'
    COMPLETED = 'was ended'
    ACTIVE = 'is active'

    SELECT_STATUS = [
        (CREATED, 'was created'),
        (COMPLETED, 'was ended'),
        (ACTIVE, 'active'),
    ]

    client_id = models.ManyToManyField(Client, verbose_name='client id')
    message = models.ForeignKey(MailingMessage, on_delete=models.CASCADE, verbose_name='message')
    time = models.TimeField(default=datetime.now, verbose_name='time')
    start = models.DateTimeField(default=datetime.now, verbose_name='start time UTC')
    finish = models.DateTimeField(default=datetime.now, verbose_name='finish time UTC')
    periodicity = models.CharField(max_length=150, choices=PERIODICITY, verbose_name='periodicity')
    status = models.CharField(max_length=100, default='was created', choices=SELECT_STATUS, verbose_name='status')
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='creator')

    def __str__(self):
        return f"{self.message.subject} have to start from {self.start.strftime('%Y-%m-%d %H:%M')} with period {self.periodicity}"

    class Meta:
        verbose_name = 'mailing list'
        verbose_name_plural = 'mailing lists'
        get_latest_by = 'time'
        permissions = [
                ('change_active', 'Can change active flag')
            ]


class MailingListLogs(models.Model):
    SENT = 'was sent'
    ERROR = 'sending error'

    STATUS = (
        (SENT, 'sent'),
        (ERROR, 'sending error'),
    )

    mailing_list_id = models.ForeignKey(MailingList, on_delete=models.CASCADE, verbose_name='mailing list id')
    client = models.ForeignKey(Client, on_delete=models.CASCADE, **NULLABLE, verbose_name='client')
    send_time = models.DateTimeField(auto_now_add=True, verbose_name='send time')
    status = models.CharField(choices=STATUS, verbose_name='status')
    response = models.TextField(**NULLABLE, verbose_name='response from server')

    def __str__(self):
        return f'{self.mailing_list_id.message.subject} was processed: {self.send_time.strftime("%Y-%m-%d %H:%M")}'

    class Meta:
        verbose_name = 'mailing effort log'
        verbose_name_plural = 'mailing efforts log'

main/forms.py
from django import forms

from main.models import MailingList, MailingMessage, Client


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field.widget, forms.widgets.CheckboxInput):
                field.widget.attrs['class'] = 'form-check-container'
            else:
                field.widget.attrs['class'] = 'form-control'


class MailingListCreationForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = MailingList
        # fields = '__all__'
        exclude = ('creator',)

    def clean_finish(self):
        finish = self.cleaned_data['finish']
        start = self.cleaned_data['start']
        if start > finish:
            raise forms.ValidationError('Attention! Finish time cannot be less then start')
        if start == finish:
            raise forms.ValidationError('Attention! Finish time need to be more then start at least 5 min')

        return finish


class MessageCreationForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = MailingMessage
        exclude = ('creator',)

class ClientCreateForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        fields = ('email', 'first_name', 'last_name', 'is_active')
        # exclude = ('creator',)

main/views.py
import random

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from blog.models import Blog
# from config.config import MAX_PRODUCTS_PER_PAGE
from main.forms import MailingListCreationForm, MessageCreationForm, ClientCreateForm
from main.models import MailingList, MailingMessage, Client, MailingListLogs
from main.services import checking_and_send_emails, get_log_data


class HomePageView(ListView):
    model = MailingList
    template_name = 'main/index.html'


# HomePage View in FBV notation
def home_page_view(request):
    blogs = Blog.objects.all()
    blogs_count = Blog.objects.count()
    if blogs_count > 3:
        selected_numbers = random.sample(list(range(blogs_count)), k=3)
        blogs = [blogs[selected_numbers[0]], blogs[selected_numbers[1]], blogs[selected_numbers[2]]]
    mailing_count = MailingList.objects.count()
    mailing_active_count = MailingList.objects.filter(status='is active').count()
    uniq_clients_count = Client.objects.all().count()
    context = {'object_list': blogs,
               'title': "Mailing service",
               'uniq_clients_count': uniq_clients_count,
               'mailing_count': mailing_count,
               'mailing_active_count': mailing_active_count}
    return render(request, 'main/index.html', context)


class MailingListView(LoginRequiredMixin, ListView):
    model = MailingList
    ordering = 'pk'

    def get_queryset(self, *args, **kwargs):
        # print(self.request.user.groups.filter(name='Managers'))
        if self.request.user.groups.filter(name='managers').exists() or self.request.user.is_superuser:
            context = super().get_queryset()
        else:
            context = MailingList.objects.filter(creator=self.request.user)
        return context

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['title'] = "Mailing service"
        context['managers'] = self.request.user.groups.filter(name='managers').exists()
        # interval = self.count_min_max_pk_on_page()
        return context


class MailingListDetailView(LoginRequiredMixin, DetailView):
    model = MailingList
    success_url = reverse_lazy('main:mailing_list')

    # permission_required = ('main.view_mailinglist', )

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['title'] = "Mailing service"
        # interval = self.count_min_max_pk_on_page()
        return context


class MailingListCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = MailingList
    form_class = MailingListCreationForm
    success_url = reverse_lazy('main:mailing_list')
    permission_required = ('main.add_mailinglist',)

    def form_valid(self, form):
        """ save data
         after that we will immediately check and send the mail if necessary """
        self.object = form.save()
        self.object.creator = self.request.user
        self.object.save()
        checking_and_send_emails()
        return super().form_valid(form)


class MailingListUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = MailingList
    template_name = 'main/mailinglist_form.html'
    success_url = reverse_lazy('main:mailing_list')
    form_class = MailingListCreationForm
    permission_required = ('main.change_mailinglist',)

    def form_valid(self, form):
        """ save new data
        after that we will immediately check and send the mail if necessary """
        self.object = form.save()
        self.object.creator = self.request.user
        self.object.save()
        checking_and_send_emails()
        return super().form_valid(form)


class MailingListDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = MailingList
    success_url = reverse_lazy('main:mailing_list')
    permission_required = ('main.delete_mailinglist',)


def mailing_activate(request, pk):
    """set status 'is active' for current object
       after that we will immediately check and send the mail if necessary """
    info = get_object_or_404(MailingList, pk=pk)
    info.status = 'is active'
    info.save()
    print(info)
    checking_and_send_emails()
    return redirect('main:mailing_list')


def mailing_deactivate(request, pk):
    """set status 'was ended' for current object"""
    obj = get_object_or_404(MailingList, pk=pk)
    obj.status = 'was ended'
    obj.save()
    return redirect('main:mailing_list')


class MessageCreateView(CreateView):
    model = MailingMessage
    form_class = MessageCreationForm
    success_url = reverse_lazy('main:mailing_create')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Message Creation"
        return context

    def form_valid(self, form):
        self.object = form.save()
        self.object.creator = self.request.user
        self.object.save()
        return super().form_valid(form)


class ClientCreateView(LoginRequiredMixin, PermissionRequiredMixin,CreateView):
    model = Client
    success_url = reverse_lazy('main:mailing_list')
    form_class = ClientCreateForm

    permission_required = ('main.view_client', )


class LogListView(ListView):
    model = MailingListLogs
    # success_url = reverse_lazy('main:mailing_list')
    fields = ('send_time', 'status', 'response')

    def get_queryset(self, *args, **kwargs):
        """ rewrite for using low-level cache"""
        return get_log_data()

main/templates/main/includes/inc_main_menu.html
<div class="col-lg-2 bg-dark">
    <div class="d-flex flex-column flex-shrink-0 p-3 text-bg-dark" style="width: 280px; height: 660px">
        <a href="{% url 'main:index' %}"
           class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
            <svg class="bi pe-none me-2" width="40" height="32">
                <use xlink:href="#home"></use>
            </svg>
            <span class="fs-4">Main menu</span>
        </a>
        <hr>
        <ul class="nav nav-pills flex-column mb-auto">
            <li class="nav-item">
                <a href="{% url 'main:index' %}" class="nav-link text-white" aria-current="page">
                    <svg class="bi pe-none me-2" width="16" height="16">
                        <use xlink:href="#home"></use>
                    </svg>
                    Main page
                </a>
            </li>

            {% if request.user.is_authenticated %}
            <li>
                <a href="{% url 'main:mailing_list' %}" class="nav-link text-white">
                    <svg class="bi pe-none me-2" width="16" height="16">
                        <use xlink:href="#speedometer2"></use>
                    </svg>
                    Mailing list
                </a>
            </li>
            <li>
                <a href="{% url 'main:client_create' %}" class="nav-link text-white">
                    <svg class="bi pe-none me-2" width="16" height="16">
                        <use xlink:href="#table"></use>
                    </svg>
                    New client
                </a>
            </li>
            {% endif %}
            {% if perms.main.view_client %}
            <li>
                <a href="{% url 'users:users_view' %}" class="nav-link text-white">
                    <svg class="bi pe-none me-2" width="16" height="16">
                        <use xlink:href="#grid"></use>
                    </svg>
                    List of Users
                </a>
            </li>
            {% endif %}
            <li>
                <a href="{% url 'main:log_view' %}" class="nav-link text-white">
                    <svg class="bi pe-none me-2" width="16" height="16">
                        <use xlink:href="#grid"></use>
                    </svg>
                    View Logs
                </a>
            </li>

{#            <li>#}
{#                <a href="{% url 'main:add_new_product' %}" class="nav-link text-white">#}
{#                    <svg class="bi pe-none me-2" width="16" height="16">#}
{#                        <use xlink:href="#grid"></use>#}
{#                    </svg>#}
{#                    Adding new product#}
{#                </a>#}
{#            </li>#}
            <li>
                <a href="{% url 'blog:blogs_view' %}" class="nav-link text-white">
                    <svg class="bi pe-none me-2" width="16" height="16">
                        <use xlink:href="#grid"></use>
                    </svg>
                    Blogging
                </a>
            </li>
        </ul>
        <hr>
        <div class="dropdown">
            {% if request.user.is_authenticated %}
                <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle"
                    data-bs-toggle="dropdown" aria-expanded="false">
                    {% if user.avatar %}
                        <img src="{{ user.avatar.url }}" alt="" width="94" height="94" class="rounded-circle me-2">
                    {% else %}
                        <img src="https://github.com/kirsansan.png" alt="" width="94" height="94" class="rounded-circle me-2">
                    {% endif %}
                    <strong>hello {{ user.email }} ({{ user.first_name }}) </strong>
                </a>
            {% else %}
                    <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle"
                    data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="https://github.com/skyprotutors.png" alt="" width="94" height="94" class="rounded-circle me-2">
                    <strong> No user </strong>
                    </a>
            {% endif %}
            <ul class="dropdown-menu dropdown-menu-dark text-small shadow">

                {% if user.is_authenticated %}
                    <li><a class="dropdown-item" href="{% url 'users:profile' %}">Profile</a></li>
                    <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
                {% else %}
                    <li><a class="dropdown-item" href="{% url 'users:login' %}">Login</a></li>
                    <li><a class="dropdown-item" href="{% url 'users:register' %}">Registration</a></li>
                {% endif %}

            </ul>
        </div>
    </div>
</div>